# Schema for the configuration files of the MBGNA Settings module.
mbgna_settings.settings:
  type: config_object
  label: 'MBGNA settings'
  mapping:
    membership_user_roles:
      type: sequence
      label: 'Select membership user roles'
      sequence:
        type: string
    privileged_user_roles:
      type: sequence
      label: 'Select privileged user roles'
      sequence:
        type: string
    staff_user_role:
      type: string
      label: 'Select the staff user role'
    intern_user_role:
      type: string
      label: 'Select the intern user role'
    author_user_role:
      type: string
      label: 'Select the author user role'
    promo_calc_pay_method:
      type: string
      label: 'Select the payment method for calcuating promotions'
    promotions_display:
      type: boolean
      label: 'Display promotions on "Add to Cart" forms'
